[package]
name = "to-pin"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { version = "0.3.31", features = ["futures-executor"] }
pin-project = "1.1.10"
tokio = { version = "1.44.0", features = ["full"] }
