[package]
name = "block-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.97"
byteorder = "1.5.0"
bytes = "1.10.1"
crc32c = "0.6.8"
crc32fast = "1.4.2"
flatbuffers = "25.2.10"
snap = "1.1.1"
tokio = { version = "1.44.0", features = ["full"] }
