[package]
edition = "2024"
name = "rust_io_uring"
version = "0.1.0"

[dependencies]
io-uring = "0.7.6"
scopeguard = "1.2.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
harness = false
name = "muilti_read"
